#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/www/{backgrounds,icons,avatars,SupportedApps} \
	/var/www/localhost/heimdall \
	/config/log/heimdall

# install heimdall if necessary
[[ -f /heimdall/heimdall.tar.gz ]] && \
 echo "New container detected, installing Heimdall" && \
 tar xf \
 	/heimdall/heimdall.tar.gz -C \
	/var/www/localhost/heimdall --strip-components=1 && \
 echo -e '\n# Heimdall user authorization\nfastcgi_param  PHP_AUTH_USER $remote_user;\nfastcgi_param  PHP_AUTH_PW $http_authorization;' >> \
	/etc/nginx/fastcgi_params && \
 rm -rf /heimdall && \
 chown -R abc:abc /var/www/localhost/heimdall

# create symlinks

symlinks=( \
/var/www/localhost/heimdall/storage/app/public/avatars \
/var/www/localhost/heimdall/storage/app/public/backgrounds \
/var/www/localhost/heimdall/storage/app/public/icons \
/var/www/localhost/heimdall/app/SupportedApps \
/var/www/localhost/heimdall/database/app.sqlite \
/var/www/localhost/heimdall/.env )

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/"$(basename "$i")" "$i"
done

[[ -e "/var/www/localhost/heimdall/storage/logs/laravel.log" && ! -L "/var/www/localhost/heimdall/storage/logs/laravel.log" ]] \
	&& rm -rf "/var/www/localhost/heimdall/storage/logs/laravel.log"
[[ ! -L "/var/www/localhost/heimdall/storage/logs/laravel.log" ]] && \
	ln -s "/config/log/heimdall/laravel.log" "/var/www/localhost/heimdall/storage/logs/laravel.log"

# copy .env if not exists
[[ ! -f /config/www/.env ]] && \
  cp /var/www/localhost/heimdall/.env.example /config/www/.env && \
  echo "Creating app key. This may take a while on slower systems" && \
  php /var/www/localhost/heimdall/artisan key:generate
# set queue driver to database
sed -i 's/QUEUE_DRIVER=sync/QUEUE_DRIVER=database/' /config/www/.env

# permissions
echo "Setting permissions"
chown -R abc:abc \
	/config
